### ISSUE TITLE
After 9.12 update, the mvt:do autocompletes the incorrect file variable

### ISSUE THREAD

**Issue by steveosoule** [mghweb/sublime-miva-ide#35] opened 2018-11-01 20:06 UTC
When i used the `mvt:do` autocompletion for `Customer_Load_Email`, it autocompleted it to: 
```<mvt:do file="g.Module_Feature_MMLSK-CUS_DB" name="l.success" value="Customer_Load_Email( pw_email, customer var )" />```
but the file name should be `g.Module_Feature_CUS_DB` instead.

I've seen the extra `MMLSK-` issue with several other function autocompletions too.

**Comment by mghweb** [comment] 2018-11-06 01:31
Fixed in latest version (3.1.7).

Was caused by a change to file names in the latest LSK version.

d58d287c9378163c219467533de03ab9cb24835d

**Closed** 2018-11-06 01:31 UTC
